### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by taowu82** [Staroon/zabbix-hadoop-template#1]
2017-11-06 18:02:23 | Traceback (most recent call last):  File "/usr/local/zabbix/share/zabbix/externalscripts/zabbix-hadoop.py", line 170, in <module>    json_processed = json_processing(json_as_dictionary, monitor_type)  File "/usr/local/zabbix/share/zabbix/externalscripts/zabbix-hadoop.py", line 78, in json_processing    namenode_dict['live_nodes'] = json_dict['beans'][9]['NumLiveDataNodes']KeyError: 'NumLiveDataNodes'ERROR
-- | --

请问你python用的啥版本，我这执行报错了

**Comment by Staroon** [comment]
这个跟Python版本没关系的，是由于集群这个地址  <http://name_node_ip:50070/jmx?qry=Hadoop:*>  的json数据不一致导致的，可能是因为Hadoop版本不一致。报错出现在78行，那就是**NumLiveDataNodes**这个json串位置变了，后面的监控指标估计也不一样，你可以分析一下你的集群的这个json数据，然后修改下zabbix-hadoop.py脚本就行了。
